---
- name: Install and set up all major applications on my system
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - gnome
    - network
    - bluetooth
    - role: wayland
      tags: wayland
    - role: sway
      tags: wayland
    - role: i3
      tags: x11
    - ssh
    - themes
    - terminal
    - vim
    - gedit
    - firefox
    - okular
    - ark
    - slack
    - thunderbird
    - dev
    - security
    - dotfiles

