---
- name: install i3
  become: True
  package:
    name: i3
    state: present
- name: install polybar
  become: True
  package:
    name: polybar
    state: present
- name: install rofi
  become: True
  package:
    name: rofi
    state: present
- name: install i3lock
  become: True
  package:
    name: i3lock
    state: present
- name: install light
  become: True
  package:
    name: light
    state: present
- name: install feh
  become: True
  package:
    name: feh
    state: present
- name: install conky
  become: True
  package:
    name: conky
    state: present
- name: install arandr
  become: True
  package:
    name: arandr
    state: present
- name: install dunst
  become: True
  package:
    name: dunst
    state: present

